Regression test for integration bug introduced by `CatchAndThrowMethodVisitor`
The `CatchAndThrowMethodVisitor` was introduced on commit 5ec4f34 only
for exceptions that are sub-classes of `RuntimeExceptions`. On commit
44c74f2 we start handling all sub-classes of `Exception`. On commit
c81c1f2 we updated for anything extending `Throwable`. This feature was
disabled on commit 3c967c7 and using it required a system property
`badua.experimental.exception_handler` with value "true", basically a
feature toggle. Finally, all these changes were merged to mainline on
commit 9b483f1 and released on version 0.4.0 (wow, this was almost 5
years ago).

On commit 2ba7e34 the `CatchAndThrowMethodVisitor` was enabled by
default (no feature toggle required) and merged to mainline on commit
1abc38e (PR #16) and release on version 0.5.0.

So basically, this bug was introduced on version 0.4.0 disabled by
default and was enabled by default on version 0.5.0.

This bug only affects a special kind of method: the ones that have a
jump arc to the very first instruction.

*Bug Description*

Assumptions:

  1. `CoverageMethodTransformer.transform` method expects a valid
`MethodNode methodNode` parameter, and by being valid we expect that all
method's basic blocks have at least one bytecode instruction.

  2. `LabelFrameNode.insertBefore` method does not expect `null` as the
`AbstractInsnNode location` parameter and will never receive `null` on
it.

Assume the following code sequence (pseudo-bytecode):

```
label: <----------
  inst 1;        |
  inst 2;        |
  .              |
  .              |
  .              |
  goto label; ----
  .
  .
```

The `CatchAndThrowMethodVisitor` will wrap all the code with `start` and
`end` labels as follows:

```
start:
label: <----------
  inst 1;        |
  inst 2;        |
  .              |
  .              |
  .              |
  goto label; ----
  .
  .
end:
handle:
 athrow;
```

To define an Exception table as follows:

```
   from     to     target     type
   start    end    handle     java/lang/Throwable
```

The problem is that it will introduce a basic block with only a label
(start) and no bytecode instructions. So assumption number 1 will not be
held and, consequently, will also break assumption number 2. The
execution will throw the following NPE:

```
test(br.usp.each.saeg.badua.test.validation.JumpToFirstInstructionSourceTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.RuntimeException: java.io.IOException: Error while instrumenting class br.usp.each.saeg.badua.test.validation.targets.JumpToFirstInstruction.
	at br.usp.each.saeg.badua.test.validation.ValidationTest.instrument(ValidationTest.java:46)
	at br.usp.each.saeg.badua.test.validation.ValidationTest.addClass(ValidationTest.java:35)
	at br.usp.each.saeg.badua.test.validation.ValidationTargetsTest.execute(ValidationTargetsTest.java:57)
	at br.usp.each.saeg.badua.test.validation.ValidationTargetsTest.setUp(ValidationTargetsTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: Error while instrumenting class br.usp.each.saeg.badua.test.validation.targets.JumpToFirstInstruction.
	at br.usp.each.saeg.badua.core.instr.Instrumenter.instrumentError(Instrumenter.java:65)
	at br.usp.each.saeg.badua.core.instr.Instrumenter.instrument(Instrumenter.java:50)
	at br.usp.each.saeg.badua.test.validation.ValidationTest.instrument(ValidationTest.java:43)
	... 36 more
Caused by: java.lang.NullPointerException
	at br.usp.each.saeg.badua.core.internal.instr.LabelFrameNode.create(LabelFrameNode.java:59)
	at br.usp.each.saeg.badua.core.internal.instr.LabelFrameNode.insertBefore(LabelFrameNode.java:51)
	at br.usp.each.saeg.badua.core.internal.instr.CoverageMethodTransformer.transform(CoverageMethodTransformer.java:171)
	at br.usp.each.saeg.badua.core.internal.instr.MethodInstrumenter.transform(MethodInstrumenter.java:90)
	at br.usp.each.saeg.badua.core.internal.instr.MethodInstrumenter.visitEnd(MethodInstrumenter.java:73)
	at org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:783)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1518)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at br.usp.each.saeg.badua.core.instr.Instrumenter.instrument(Instrumenter.java:42)
	at br.usp.each.saeg.badua.core.instr.Instrumenter.instrument(Instrumenter.java:48)
	... 37 more
```

This commit only introduces regressions tests to reproduce the problem.